"""add images table

Revision ID: 0e4297a8f5e3
Revises: d51ed6822e8d
Create Date: 2025-05-25 23:47:50.686616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e4297a8f5e3'
down_revision: Union[str, None] = 'd51ed6822e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cloud_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('owner_team', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_path')
    )
    op.alter_column('api_key', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_key', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('api_key', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('team', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint('team_name_key', 'team', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_name_key', 'team', type_='unique')
    op.alter_column('team', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_key', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('api_key', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_key', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('image')
    # ### end Alembic commands ###
