version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: .devops/docker/api/dev/Dockerfile
    container_name: image_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/image_db
    depends_on:
      - db
    healthcheck:
      test: "curl -f http://localhost:8000/health"
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=image_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
