[project]
name = "image-manager"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.41",
]

[dependency-groups]
dev = [
    "ruff>=0.11.11",
]
