"""revised unique constraints

Revision ID: 4e3315b4f680
Revises: 0e4297a8f5e3
Create Date: 2025-05-27 10:37:43.526554

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4e3315b4f680"
down_revision: Union[str, None] = "0e4297a8f5e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("app_user_email_key"), "app_user", type_="unique")
    op.drop_constraint(op.f("team_name_key"), "team", type_="unique")
    # ### end Alembic commands ###
    op.execute(
        """CREATE UNIQUE INDEX team_name_active_true_idx ON team(name) WHERE active = true;"""
    )
    op.execute(
        """CREATE UNIQUE INDEX app_user_email_active_true_idx ON app_user(email) WHERE active = true;"""
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("app_user_email_active_true_idx", table_name="app_user")
    op.drop_index("team_name_active_true_idx", table_name="team")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("team_name_key"), "team", ["name"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("app_user_email_key"),
        "app_user",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
