name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        working-directory: apps/image_api
        run: uv sync
      - name: Run Alembic migrations
        working-directory: apps/image_api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          alembic upgrade head
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
        working-directory: .devops/terraform
      - name: Terraform Plan
        run: terraform plan
        working-directory: .devops/terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .devops/terraform